### ISSUE TITLE
Avatars sometimes show, sometimes they disappear.

### ISSUE THREAD

**Issue by gblackiv** [Learning-Fuze/c718_partytodoplanner#191]
the avatars on list items are very inconsistent.

**Comment by toriep** [comment]
The axios call is not on sync and unable to catch up with the checking and unchecking. Perhaps disable check and uncheck until axios is completed

**Comment by toriep** [comment]
When connection is slow, avatar displaying is more frequently inconsistent

**Comment by gblackiv** [comment]
changed the issue to now the internet being slow stops the the user from clicking many times.
